# ________________________________________________
#
#       CHAMPION TICKETS LANGUAGE FILE
#
# Here you can customise Bot's Messages.
#
# ________________________________________________

general:
  cannot_self: "You cannot use this command on yourself."
  # Available Placeholders: <role>
  no_role: "You need <role> Role to use this command."
  not_set: "You don't have that option set so it cannot be reseted." 
  cmd_disabled: "This command is disabled on this server."
  no_perm: "You don't have permission to perform this command." 
  usage: "Invalid Usage for Command. Usage: `<usage>`"
  ping_loading: "Ping.."
  ping: "Bot Uptime is <uptime>, bot ping <bot>ms, api ping <api>ms"
  auto_response: "Hey <user>, <response>."
  auto_announce: "<message>."
  cooldown: "You're on cooldown on that command for <cooldown>"
  invalid_cmd: "You have provided Invalid Command"
  no_commands: "No Commands in this Category"
  no_suggest: "Suggestions Channel isn't setuped yet."
  suggestions:
    accepted: "Suggestion have been accepted successfully"
    denied: "Suggestion have been denied successfully"
    deleted: "Suggestion have been deleted successfully"
    sent: "Your Suggestion have been successfully sent."
    vote_yes: "You have UpVoted this Suggestion."
    vote_no: "You have DownVoted this Suggestion."
    vote_reset: "Your Vote have been reseted."
    placeholder: "Select decision option for this Suggestion"
    decision:
      accept: "Accept Suggestion"
      deny: "Deny Suggestion"
      delete: "Delete Suggestion"
    not_voted: "You cannot reset Vote because you didn't vote."
    already_voted: "You have already voted, please reset your Vote"
    decision_reason: "Suggestion decision reason have been added."
  paypal_cred: "PayPal API Secret Token or Client ID from config.yml are invalid."
  dm_closed: "Your DMs or DMs of other user are closed."
buttons:
  confirm_close: "Yes, I'm sure"
  cancel_close: "No, don't close it yet"
  create: "Create Ticket"
  close: "Close Ticket"
  go_ticket: "Go to Ticket"
  next: "Next"
  previous: "Previous"
  download: "Download"
  link: "Get Link"
  # Available Placeholders: <count> (For both yes_vote & no_vote - Number of Votes)
  yes_vote: "<count>"
  no_vote: "<count>"
  remove_vote: "Remove Vote"
  transcripts:
    download: "Download Transcript"
    view: "View Transcript"
  answer_questions: "Answer Questions #<page>"
  answered_all: "Questions Answered"
  paypal: "Pay Order"
  invoice: "Pay Invoice"
  quote: "Accept Quote"
  withdraw_yes: "Accept Withdraw"
  withdraw_no: "Deny Withdraw"
  send_withdraw: "Send Withdraw"
  claim: "Claim Ticket"
  send_quote: "Quote"
  reply_message: "Reply"
  message_client: "Message Client"
  cancel_review: "Cancel Review"
titles:
  help: "üöÄ ¬∑ Help Menu"
  error: "Error"
  auto_response: "Auto Response"
  auto_announce: "Auto Announce"
  closed_dm: "Thank you for contacting us"
  answers: "Answers"
  # Available Placeholders: <page> (Current Page), <max> (Number of Pages)
  questions: "Ticket Questions (<page>/<max>)"
  products: "List of Products Available"
  sugg_accepted: "Suggestion accepted"
  sugg_denied: "Suggestion denied"
  sugg_label: "Suggestion Text"
  setprofile: "Profile Customisation"
  notes: "Channel Notes"
  review: "Review User"
  commission: "New Commission"
  quote: "Quote"
  message_client: "Message Client"
  reply_comm: "Reply to Message"
  accept_reason: "Accept Reason"
  deny_reason: "Deny Reason"
modals:
  placeholders:
    bio: "Set your bio."
    paypal: "Set your PayPal Email"
    hours: "Set time you're available"
    suggestion: "Enter Text of your Suggestion"
    notes: "Enter Note for this Channel"
    review: "Choose rating for user"
    comment: "Comment for this Review"
    comm_price: "How much money would you request for this?"
    comm_time: "How much time would you need to finish this?"
    comm_note: "Do you have any notes regarding this commission?"
    message_client: "What would you like to ask client?"
    reply_comm: "What would you like to reply with to message?"
    decision: "What's reason for this decision?"
    portfolio: "Set your portfolio."
  # Titles/Labels
  labels:
    bio: "Biography"
    paypal: "PayPal Email"
    hours: "Available Hours"
    notes: "Add Notes"
    comment: "Add Review Comment"
    comm_price: "Price"
    comm_time: "Time Frame"
    comm_note: "Quote Notes"
    message_client: "Message Client"
    reply_comm: "Reply to Message"
    decision: "Decision Reason"
    portfolio: "Portfolio"
ticket:
  already_open: "Sorry, you already have an ticket opened, close it before opening another."
  have_in_sel: "You already have an ticket waiting for Category Selection, close it or select category."
  no_category: "Category for tickets isn't setuped yet, ticket couldn't be opened."
  no_panel: "Panel Channel isn't setuped."
  no_transcript: "Channel for Transcripts isn't setuped yet but transcripts are enabled."
  user_added: "You have successfully added <user> to the ticket."
  user_removed: "You have successfully removed <user> from the ticket."
  ticket_channel: "This command can only be used in Tickets Channel."
  close_confirmation: "Are you sure you want to close ticket? Click on Button to Confirm your decision."
  bl_role: "You cannot open Ticket because you have role which is Blacklisted from opening them."
  bl_user: "You cannot open Ticket because you are Blacklisted from opening them."
  ticket_created: "Hey <user>, your Ticket have been created in channel <channel>."
  time_expired: "Time for decision has passed without answer, ticket won't be deleted."
  ticket_deleted: "Ticket will be deleted in few seconds.."
  cancel_delete: "You have successfully canceled ticket deletation."
  channel_topic: "Ticket opened by <author>."
  have_ticket_category: "You already have maximum number of opened tickets in that category."
  already_claimed: "This Ticket is already claimed"
  ticket_claimed: "Ticket have been claimed by <user>"
  ticket_assigned: "Ticket have been assigned to <user> by <author>."
  invalid_category: "You have provided Invalid Category Name/ID"
  category_moved: "Ticket have been moved to <category> Category by <user>"
  not_separate: "Config Fields 'separateCategories' & 'category > status' need to be enabled in order to use this Command."
  move_topic: "Ticket have been moved to <category> by <user>"
  closed_dm: "Hey, thank you for contacting us. We will be grateful if you review your seller using `-review` Command."
  loading_answers: "Loading Answers, please wait."
  question_idle: "Time to answer questions have expired, you can no longer answer"
  panel_created: "Ticket Panel have been created successfully."
  transcript_code: "Web Transcript Code of Transcript with ID `<transcript>` is `<code>`."
  priority:
    changed: "Priority of Ticket Channel <channel> have been changed to <priority>."
    invalid: "You have entered invalid priority. Valid: Low, Normal, High, Urgent."
    list: "**Urgent Priority**:\n<urgent>\n\n**High Priority**:\n<high>"
    no_high: "> No High Priority Tickets"
    no_urgent: "> No Urgent Priority Tickets"
  invalid_panel: "Ticket couldn't be created because such Ticket Category doesn't exist."
  answered_set: "You have answered set of ticket questions, click button again to answer remaining questions."
  answered_all: "All questions have been answered, thank you."
  transcript_prompt: "Enter Transcript Access Code (exit to close):"
  reask: "Process for Question Answering have been restarted and questions will be asked again."
  not_answered: "Questions haven't been answered in this ticket."
  # Available Placeholders: <user>, <startFormatted>, <endFormatted>, <start> & <end>
  not_available: "Hello <user>, currently we are not available, our availability time is from <startFormatted> to <endFormatted>, please be patient."
  creation: "Creation Date: "
  closing: "Closing Date: "
utility:
  getid: "ID of <type> is `<id>`."
  counters_started: "Counters have started creating, please wait."
  counters_created: "Counters have been created."
  claimed_counter: "Claimed Tickets: <stats>"
  total_counter: "Total Tickets: <stats>"
  opened_counter: "Open Tickets: <stats>"
  counters_category: "Tickets Statistics"
  math_error: "An Error occurred during calculation."
service:
  invalid_mail: "You have entered invalid Email."
  no_review: "Review with that ID cannot be found."
  review_self: "You cannot Review yourself"
  status: "Your Freelancer Status have been changed to __<status>__."
  availability:
    available: "Available"
    unavailable: "Unavailable"
  no_paypal: "No PayPal Set"
  no_hours: "No Available Hours"
  no_portfolio: "No Portfolio Set"
  note_added: "Channel Note have been changed to `<note>`."
  note_reseted: "Channel Note have been reseted."
  profile_updated: "Your profile have been updated successfully with new entries."
  hours_added: "Available Hours have been changed to `<hours>`."
  hours_reseted: "Available Hours have been reseted."
  paypal_added: "Your PayPal have been changed to `<paypal>`."
  paypal_reseted: "Your PayPal have been reseted."
  bio_added: "Your Bio have been changed to `<bio>`." 
  bio_reseted: "Your Bio have been reseted."
  invalid_crypto: "You have entered Invalid Crypto Currency"
  invalid_invoice: "You have provided Invalid Invoice ID"
  invalid_portfolio: "You have provided invalid portfolio, make sure it's not too long & that it's link."
  portfolio_added: "Your Portfolio have been changed to `<portfolio>`." 
  portfolio_reseted: "Your Portfolio have been reseted."
  reviews:
    rating: "Review process has started. Select rating for this User from Drop Down menu. After that you'll be prompted to enter comment."
    rating_dm: "Hey, we noticed your ticket has been recently closed on our Server.\nWe would like to know how much you're satisfied with our Support by choosing rating from drop down menu.\nTo cancel just type 'cancel'"
    placeholder: "Please select rating from 1 - 5 ‚≠ê from drop down menu or cancel review."
    sent: "Thank you for your response! Review have been sent successfully."
    time: "Time for providing comment/rating has passed, review process canceled."
    cannot_review: "You cannot review that User"
    cancel: "Review Process have been canceled"
    no_comment: "No comment provided."
    stars:
      one: "One Star"
      two: "Two Stars"
      three: "Three Stars"
      four: "Four Stars"
      five: "Five Stars"
  commission:
    no_time_frame: "No Time Frame"
    no_notes: "No Quote Notes"
    not_commission : "This ticket channel is not of Commission Type or commission have been completed."
    no_data: "Ticket Questions haven't been answered, you cannot give quote."
    marked: "Commission have been marked as <type> by <user>."
    complete: "Commission have been marked as complete, freelancer <freelancer> has gained <currency><taxAmount> of total <currency><fullAmount> (<percentage>%)."
    no_quote: "User didn't accept any quote, you can't mark this commission as complete."
    quote_sent: "You have successfully quoted this commission."
    message_sent: "Message regarding Commission <channel> have been sent to <user>."
    reply_sent: "Reply regarding Commission <channel> have been sent to <user>."
  balance: "<user>'s balance is $<balance>"
  invalid_amount: "You don't have enough money in bank for this action."
  invalid_withdraw: "User doesn't have enough money for withdraw"
  withdraw_request: "Your withdraw request with amount of $<amount> have been sent successfully, please wait for answer."
  withdraw_accepted: "You have successfully accepted <user>'s withdraw of $<amount>, please send money."
  withdraw_accepted_dm: "Hey <user>, your withdraw of $<amount> have been accepted by <acceptedBy>."
  withdraw_denied: "You have denied <user>'s withdraw of $<amount>."
  withdraw_denied_dm: "Hey <user>, your withdraw of $<amount> have been denied by <acceptedBy>."
  no_mail: "You don't have PayPal Email set."
  no_withdraw_channel: "There is no withdraw request channel setuped, contact staff."
  withdraw_reason: "Withdraw Request sent by <user>"
  taxes_format: "<name> - <amount>"
  data_edited: "Data of <target> have been edited successfully."
  client_info: "Client Information about <user>\n\n>>> **Number of Orders:** <orderCount>\n**Total Amount Spent:** $<amountSpent>"
  price_edited: "Price of this commission have been changed to <currencySymbol><amount> by <user>."
products:
  # Available Placeholders: <file> (Name of File)
  download_get: "Click on Button below to get download for your file (<file>)"
  # Available Placeholders: <link> (Name of Link)
  link_get: "Click on Button below to get your link (<link>)"
  # Available Placeholders: <file> (Name of File)
  download: "Click on Button below to download your file (<file>)"
  # Available Placeholders: <link> (Name of Link)
  link: "Click on Button below to go to your link (<link>)"
  # Available Placeholders: <role> (List of Required Roles)
  roles: "You need <role> Role(s) to be able do get this product"
  permissions: "You don't have permission to get this product"
  invalid_product: "Product with such ID doesn't exist"
  none_type: "This Product cannot be downloaded."
  error: "An Error happened, maybe you invalid Product was provided in config or it doesn't exist."
sellix:
  invalid_key: "Sellix API Key provided is invalid."
  no_id: "Order with such ID couldn't be found"
  used_id: "Someone has already been verified with that Order ID"
  # Available Placeholders: <product> (Product Purchased), <roles> (Roles Obtained)
  verified: "You have successfully connected your Discord with Purchase of <product> on Sellix"
  no_product: "Product couldn't be found."
  no_roles: "Server doesn't have any roles for verification setuped, you cannot be verified."
tebex:
  no_id: "Transaction with such ID couldn't be found"
  used_id: "Someone has already been verified with that Transaction ID"
  # Available Placeholders: <packages> (Packages Purchased), <roles> (Roles Obtained)
  verified: "You have successully connected your Discord with Purchase of <packages> Package(s) on Tebex."
  no_roles: "Server doesn't have any roles for verification setuped, you cannot be verified."
cstore:
  no_id: "Transaction with such ID couldn't be found"
  used_id: "Someone has already been verified with that Transaction ID"
  # Available Placeholders: <packages> (Packages Purchased), <roles> (Roles Obtained)
  verified: "You have successully connected your Discord with Purchase of <packages> Package(s) on CraftingStore."
  no_roles: "Server doesn't have any roles for verification setuped, you cannot be verified."
  no_package: "No Package Found."
dashboard:
  title: "Champion Tickets Dashboard"
  not_found: "This page couldn't be found."
  forbidden: "You don't have access to this page, if you think this is an error, please contact server owner."
  welcome: "Welcome to Dashboard, to continue login with your Discord Account."
  login: "Login with Discord"
  home: "Home Page"
  no_users: "No Users Added"
  no_tickets: "There are no Tickets open."
  no_transcripts: "There are no Transcripts saved."
  no_balances: "There are no users with balance"
  tickets_list: "List of Tickets"
  transcripts_list: "List of Transcripts"
  no_logs: "There are no logs."
  profile: "Profile"
  navbar:
    home: "Home"
    ticketing: "Ticketing"
    settings: "Settings"
    logs: "Logs"
    invoice: "Invoicing"
    profile: "Profile"
    logout: "Logout"
  titles:
    total: "Total Tickets"
    income: "Total Income"
    invoices: "Invoices Paid"
    commissions: "Active Commissions"
    members: "Member Count"
    dash_logs: "Dashboard Logs"
    server_logs: "Server Logs"
    save: "Save"
    delete: "Delete"
    access: "Access"
    add: "Add/Remove User"
    current_users: "Current Users"
    balances: "Balances"
    paypal: "PayPal Address"
    portfolio: "Portfolio Link"
    hours: "Availability Hours"
    bio: "Your Bio"
    rating: "Your Review Rating"
    invoices_page: "Invoices"
    commands: "Commands"
    config: "Basic Configuration"
  invoice:
    id: "Invoice ID"
    author: "Author"
    user: "User"
    amount: "Amount"
    date: "Date"
    actions: "Actions"
    filter: "Filter Invoices"
  # To make word bold put double asterisk (**) around it, to make it semibold put equal sign (=) around it
  # Available Placeholders: [DATE], [AUTHOR], [AUTHOR_ID], [USER], [USER_ID], [AMOUNT] (for balance_add & balance_remove),
  # [INVOICE_ID] & [INVOICE_AMOUNT] (for invoice_paid, invoice_created), [CHANNEL_ID], [CHANNEL_NAME], [CURRENCY],
  # [VALUE] & [OPTION] (For Dashboard Edit Config & Toggle Command) & [TICKET]
  logs:
    balance_add: "[DATE] **[AUTHOR]** added **[CURRENCY][AMOUNT]** to **[USER]**'s balance"
    balance_remove: "[DATE] **[AUTHOR]** removed **[CURRENCY][AMOUNT]** from **[USER]**'s balance"
    invoice_paid: "[DATE] Invoice with ID [INVOICE_ID] have been paid by **[USER]** ([CHANNEL_NAME])"
    invoice_created: "[DATE] **[AUTHOR]** generate Invoice ([INVOICE_ID]) for **[USER]**"
    ticket_add: "[DATE] **[USER]** have been added to Ticket [CHANNEL_NAME] by **[AUTHOR]**"
    ticket_remove: "[DATE] **[USER]** have been removed from Ticket [CHANNEL_NAME] by **[AUTHOR]**"
    ticket_create: "[DATE] New Ticket have been opened by **[AUTHOR]** ([CHANNEL_NAME])"
    ticket_close: "[DATE] **[AUTHOR]** has closed Ticket with ID **[TICKET]** ([CHANNEL_ID])"
    mark_complete: "[DATE] **[AUTHOR]** has marked Commission [CHANNEL_NAME] as completed (#**[TICKET]**)"
    dash_added: "[DATE] **[AUTHOR]** has granted **[USER]** access to Dashboard."
    dash_removed: "[DATE] **[AUTHOR]** has removed **[USER]**'s' access to Dashboard."
    dash_ticket_del: "[DATE] **[AUTHOR]** deleted ticket **[TICKET]**"
    dash_balance_change: "[DATE] **[AUTHOR]** has changed **[USER]**'s balance to **[CURRENCY][AMOUNT]**"
    dash_login: "[DATE] **[AUTHOR]** has logged in into dashboard"
    dash_logout: "[DATE] **[AUTHOR]** has logged out from dashboard"
    dash_edit_cfg: "[DATE] **[AUTHOR]** has edited config field **[OPTION]**"
    dash_toggle_cmd: "[DATE] ** [AUTHOR]** has toggled command **[OPTION]** [VALUE]"